language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  - "pypy3"
env:
  global:
    - COVERAGE_CMD="coverage run --append --source bienvenue,tests -m"
    - COVERAGE_DEP=coverage
install:
  # install tox-travis explicitly after tox to avoid
  # pkg_resources.VersionConflict, see
  # https://travis-ci.org/scampersand/bienvenue/jobs/196462565
  # https://github.com/ryanhiebert/tox-travis/issues/26
  - pip install tox
  - pip install tox-travis
  - pip install coveralls
script:
  - tox
after_script:
  - coveralls
